### ISSUE TITLE
jekyll spaceship breaks the jekyll build --config flag

### ISSUE THREAD

**Issue by wbsmolen** [jeffreytse/jekyll-spaceship#11]
```
    def self.load(filename = '_config.yml')
      config = deep_merge(
        { CONFIG_NAME => DEFAULT_CONFIG },
        YAML.load_file(File.expand_path(filename))
      )[CONFIG_NAME]
      @@store = config
      self.use_processors(config)
    end
````

from https://github.com/jeffreytse/jekyll-spaceship/blob/master/lib/jekyll-spaceship/cores/config.rb

the `filename` variable should equate to the --config flag value passed through from jekyll build

````
$ bundle exec jekyll build --config _configprod.yml --destination ./dist --trace
Configuration file: /mnt/c/git/fta-kb/_configprod.yml
  Jekyll Spaceship: 🚀 Jekyll-Spaceship 0.7.0
  Jekyll Spaceship: 🎉 A Jekyll plugin to provide powerful supports.
  Jekyll Spaceship: 👉 https://github.com/jeffreytse/jekyll-spaceship
Traceback (most recent call last):
        27: from /usr/local/bin/jekyll:23:in `<main>'
        26: from /usr/local/bin/jekyll:23:in `load'
        25: from /var/lib/gems/2.5.0/gems/jekyll-4.0.1/exe/jekyll:15:in `<top (required)>'
        24: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        23: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        22: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        21: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        20: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        19: from /var/lib/gems/2.5.0/gems/jekyll-4.0.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        18: from /var/lib/gems/2.5.0/gems/jekyll-4.0.1/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
        17: from /var/lib/gems/2.5.0/gems/jekyll-4.0.1/lib/jekyll/command.rb:89:in `each'
        16: from /var/lib/gems/2.5.0/gems/jekyll-4.0.1/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'  
        15: from /var/lib/gems/2.5.0/gems/jekyll-4.0.1/lib/jekyll/commands/build.rb:30:in `process'
        14: from /var/lib/gems/2.5.0/gems/jekyll-4.0.1/lib/jekyll/commands/build.rb:30:in `new'
        13: from /var/lib/gems/2.5.0/gems/jekyll-4.0.1/lib/jekyll/site.rb:34:in `initialize'
        12: from /var/lib/gems/2.5.0/gems/jekyll-4.0.1/lib/jekyll/site.rb:124:in `setup'
        11: from /var/lib/gems/2.5.0/gems/jekyll-4.0.1/lib/jekyll/plugin_manager.rb:22:in `conscientious_require'
        10: from /var/lib/gems/2.5.0/gems/jekyll-4.0.1/lib/jekyll/plugin_manager.rb:30:in `require_gems'
         9: from /var/lib/gems/2.5.0/gems/jekyll-4.0.1/lib/jekyll/external.rb:57:in `require_with_graceful_fail'
         8: from /var/lib/gems/2.5.0/gems/jekyll-4.0.1/lib/jekyll/external.rb:57:in `each'
         7: from /var/lib/gems/2.5.0/gems/jekyll-4.0.1/lib/jekyll/external.rb:60:in `block in require_with_graceful_fail' 
         6: from /var/lib/gems/2.5.0/gems/jekyll-4.0.1/lib/jekyll/external.rb:60:in `require'
         5: from /var/lib/gems/2.5.0/gems/jekyll-spaceship-0.7.0/lib/jekyll-spaceship.rb:9:in `<top (required)>'
         4: from /var/lib/gems/2.5.0/gems/jekyll-spaceship-0.7.0/lib/jekyll-spaceship.rb:11:in `<module:Spaceship>'       
         3: from /var/lib/gems/2.5.0/gems/jekyll-spaceship-0.7.0/lib/jekyll-spaceship/cores/config.rb:44:in `load'        
         2: from /usr/lib/ruby/2.5.0/psych.rb:497:in `load_file'
         1: from /usr/lib/ruby/2.5.0/psych.rb:497:in `open'
/usr/lib/ruby/2.5.0/psych.rb:497:in `initialize': No such file or directory @ rb_sysopen - /mnt/c/git/fta-kb/_config.yml (Errno::ENOENT)
````

**Comment by jeffreytse** [comment]
Hi, @wbsmolen 

🎉 The latest gem version [v0.7.1](https://rubygems.org/gems/jekyll-spaceship/versions/0.7.1) has been released.

Thanks and regards

**Comment by wbsmolen** [comment]
thanks so much! <3
