### ISSUE TITLE
0.9.8 version has error in emoji-processor

### ISSUE THREAD

**Issue by honggaruy** [jeffreytse/jekyll-spaceship#44]
I tried your another project named 'jekyll-deploy-action'.
I got some error in the process of the workflow running.
But I noticed that `jekyll-spaceship` version was different between github (0.9.8) and local machine (0.9.7).
So I updated `jekyll-spaceship` to `0.9.8` version on my local `windows 10` machine too. 

Now I got the same error on the local machine too.

Can I use the `0.9.8` version ?  
( There was no problem when I was using `0.9.7` version at today morning..)

```
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x64-mingw32]
Configuration file: D:/repository/honggaruy.github.io/_config.yml
  Jekyll Spaceship: 🚀 Jekyll-Spaceship 0.9.8
  Jekyll Spaceship: 🎉 A Jekyll plugin to provide powerful supports.
  Jekyll Spaceship: 👉 https://github.com/jeffreytse/jekyll-spaceship
  Jekyll Spaceship: 🗂  use table-processor
  Jekyll Spaceship: 🗂  use mathjax-processor
  Jekyll Spaceship: 🗂  use plantuml-processor
  Jekyll Spaceship: 🗂  use mermaid-processor
  Jekyll Spaceship: 🗂  use polyfill-processor
  Jekyll Spaceship: 🗂  use media-processor
  Jekyll Spaceship: 🗂  use emoji-processor
  Jekyll Spaceship: 🗂  use element-processor
            Source: D:/repository/honggaruy.github.io
       Destination: D:/repository/honggaruy.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
  Jekyll Spaceship: [TableProcessor] _posts/2020/2020-04-28-todays-ideas.md
  Jekyll Spaceship: [TableProcessor] _posts/2020/2020-06-04-todays-ideas.md
  Jekyll Spaceship: [TableProcessor] _posts/2020/2020-11-23-week-48th.md
  Jekyll Spaceship: [TableProcessor] _posts/2020/2020-12-07-week-50th.md
  Jekyll Spaceship: [EmojiProcessor] _posts/2020/2020-12-28-week-53th.md
  Jekyll Spaceship: [TableProcessor] _posts/2021/2021-01-01-week-01th.md
  Jekyll Spaceship: [MediaProcessor] _posts/2021/2021-01-18-week-03th.md
  Jekyll Spaceship: [MediaProcessor] _posts/2021/2021-02-01-week-05th.md
  Jekyll Spaceship: [EmojiProcessor] _wiki/vim-folding.md
  Jekyll Spaceship: [TableProcessor] _wiki/wiki-toc2side.md
  Jekyll Spaceship: [TableProcessor] _wiki/css-meaning.md
  Jekyll Spaceship: [EmojiProcessor] _wiki/sed-problem-solving.md
  Jekyll Spaceship: [MathjaxProcessor] _wiki/sed-problem-solving.md
  Jekyll Spaceship: [MathjaxProcessor] _wiki/Git-Category.md
  Jekyll Spaceship: [MathjaxProcessor] _wiki/apps-script-starter.md
  Jekyll Spaceship: [TableProcessor] _wiki/windows-terminal-config.md
  Jekyll Spaceship: [MathjaxProcessor] _wiki/Windows-Sysinternals.md
  Jekyll Spaceship: [TableProcessor] _wiki/book-developer-writing.md
  Jekyll Spaceship: [TableProcessor] _wiki/book-how-javascript-works.md
  Jekyll Spaceship: [TableProcessor] _wiki/re2-translation.md
  Jekyll Spaceship: [MathjaxProcessor] _wiki/re2-translation.md
  Jekyll Spaceship: [TableProcessor] _wiki/book-refactoring-2nd.md
  Jekyll Spaceship: [PolyfillProcessor] _wiki/wiki-jekyll-spaceship.md
  Jekyll Spaceship: [PlantumlProcessor] _wiki/wiki-jekyll-spaceship.md
  Jekyll Spaceship: [MermaidProcessor] _wiki/wiki-jekyll-spaceship.md
  Jekyll Spaceship: [MediaProcessor] _wiki/wiki-jekyll-spaceship.md
  Jekyll Spaceship: [EmojiProcessor] _wiki/wiki-jekyll-spaceship.md
  Jekyll Spaceship: [TableProcessor] _wiki/wiki-jekyll-spaceship.md
  Jekyll Spaceship: [MathjaxProcessor] _wiki/wiki-jekyll-spaceship.md
  Jekyll Spaceship: [EmojiProcessor] _wiki/OpenApi-usage.md
  Jekyll Spaceship: [TableProcessor] _wiki/meet-puppeteer.md
                    ------------------------------------------------
      Jekyll 4.1.1   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------
Traceback (most recent call last):
        35: from C:/tools/ruby27/bin/jekyll:23:in `<main>'
        34: from C:/tools/ruby27/bin/jekyll:23:in `load'
        33: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/exe/jekyll:15:in `<top (required)>'
        32: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        31: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        30: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        29: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        28: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        27: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        26: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        25: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `each'
        24: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        23: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:36:in `process'
        22: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:65:in `build'
        21: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:28:in `process_site'
        20: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:75:in `process'
        19: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/profiler.rb:41:in `profile_process'
        18: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/profiler.rb:41:in `each'
        17: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/profiler.rb:43:in `block in profile_process'
        16: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:208:in `render'
        15: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:523:in `render_pages'
        14: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:523:in `each'
        13: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:524:in `block in render_pages'        
        12: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:533:in `render_regenerated'
        11: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/page.rb:181:in `trigger_hooks'
        10: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/hooks.rb:98:in `trigger'
         9: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/hooks.rb:98:in `each'
         8: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/hooks.rb:99:in `block in trigger'
         7: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-spaceship-0.9.8/lib/jekyll-spaceship/cores/manager.rb:42:in `block in hook'
         6: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-spaceship-0.9.8/lib/jekyll-spaceship/cores/manager.rb:32:in `block in hook'
         5: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-spaceship-0.9.8/lib/jekyll-spaceship/cores/manager.rb:60:in `dispatch'
         4: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-spaceship-0.9.8/lib/jekyll-spaceship/cores/manager.rb:60:in `each'
         3: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-spaceship-0.9.8/lib/jekyll-spaceship/cores/manager.rb:61:in `block in dispatch'
         2: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-spaceship-0.9.8/lib/jekyll-spaceship/cores/processor.rb:132:in `dispatch'
         1: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-spaceship-0.9.8/lib/jekyll-spaceship/processors/emoji-processor.rb:19:in `on_handle_html'
C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/jekyll-spaceship-0.9.8/lib/jekyll-spaceship/processors/emoji-processor.rb:43:in `emoji_filter': undefined method `css' for nil:NilClass (NoMethodError)

```

**Comment by jeffreytse** [comment]
Hi @honggaruy 

Could you run this command `gem list nokogiri` and provide me you local nokogiri gem's version?

Thanks and regards

**Comment by honggaruy** [comment]
Here it is
```
D:\repository\honggaruy.github.io>gem list nokogiri

*** LOCAL GEMS ***

nokogiri (1.11.2 x64-mingw32, 1.10.10 x64-mingw32)

D:\repository\honggaruy.github.io>
```

**Comment by jeffreytse** [comment]
Hi @honggaruy 

Thanks for the reporting and this issue has been address and fixed. Please update your plugin with the repository's master branch in the `Gemfile` as below snippet. : )

```ruby
gem 'jekyll-spaceship', git: 'https://github.com/jeffreytse/jekyll-spaceship'
```

Thanks and regards

**Comment by honggaruy** [comment]
Thanks ! Your solution worked well !
